name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH keys
      run: |
        echo '${{ secrets.REMOTE_SSH_KEY }}' > /dev/shm/remote_ssh_key
        chmod 600 /dev/shm/remote_ssh_key
        echo '${{ secrets.VPN_REMOTE_SSH_KEY }}' > /dev/shm/vpn_ssh_key
        chmod 600 /dev/shm/vpn_ssh_key

    - name: Deploy to server
      run: |
        # WireGuardインターフェース名
        WG_INTERFACE="wg0"

        # VPN経由でアクセス可能なディレクトリ
        TARGET_DIR="Public/happyworld"

        # VPN接続された端末のIPアドレス
        VPN_TARGET_IP="10.0.0.2"

        # リモートサーバーにリポジトリを一時的にコピー
        REMOTE_TEMP_DIR="/tmp/your-repo"
        rsync -avz --delete $GITHUB_WORKSPACE/ $REMOTE_TEMP_DIR/

        # リポジトリをVPN接続された端末のディレクトリにコピー
        rsync -avz --delete -e "ssh -p 22 -i /dev/shm/remote_ssh_key -o 'ProxyJump ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:22 -i /dev/shm/vpn_ssh_key'" $REMOTE_TEMP_DIR/ ${{ secrets.VPN_REMOTE_USER }}@$VPN_TARGET_IP:$TARGET_DIR/

        # 一時ファイルと一時ディレクトリを削除
        rm -f /dev/shm/remote_ssh_key
        rm -f /dev/shm/vpn_ssh_key
        rm -rf $REMOTE_TEMP_DIR
